const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SCHOOL: 'SCHOOL',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'STUDENT',
  FAMILY: 'FAMILY',
});

const CENTER_TYPES = Object.freeze({
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  PRIMARY_SECONDARY: 'PRIMARY_SECONDARY',
  OTHER: 'OTHER',
});

const ACADEMIC_YEAR_STAGES = Object.freeze({
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  BACHILLERATO: 'BACHILLERATO',
  OTHER: 'OTHER',
});

const CENTER_ASSIGNMENT_ROLES = Object.freeze({
  SCHOOL_MANAGER: 'SCHOOL_MANAGER',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'STUDENT',
  FAMILY: 'FAMILY',
  OTHER: 'OTHER',
});

const GROUP_ASSIGNMENT_ROLES = Object.freeze({
  TUTOR: 'TUTOR',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'STUDENT',
  FAMILY: 'FAMILY',
  OTHER: 'OTHER',
});

const PUBLIC_USER_FIELDS = [
  'id',
  'name',
  'email',
  'role',
  'isActive',
  'schoolId',
  'groupId',
  'ageRange',
  'createdAt',
  'updatedAt',
];

module.exports = {
  ROLES,
  CENTER_TYPES,
  ACADEMIC_YEAR_STAGES,
  CENTER_ASSIGNMENT_ROLES,
  GROUP_ASSIGNMENT_ROLES,
  PUBLIC_USER_FIELDS,
};
