const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SCHOOL: 'SCHOOL',
  TEACHER: 'TEACHER',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'STUDENT',
  FAMILY: 'FAMILY',
});

// Preferencia visual del compañero. No representa el género del usuario.
const UNICORN_GENDERS = Object.freeze({
  MASCULINE: 'MASCULINE',
  FEMININE: 'FEMININE',
});

const CENTER_TYPES = Object.freeze({
  PRIMARY: 'PRIMARIA',
  SECONDARY: 'SECUNDARIA',
  PRIMARY_SECONDARY: 'PRIMARIA_SECUNDARIA',
  OTHER: 'OTRO',
});

const ACADEMIC_YEAR_STAGES = Object.freeze({
  PRIMARY: 'PRIMARIA',
  SECONDARY: 'SECUNDARIA',
  BACHILLERATO: 'BACHILLERATO',
  OTHER: 'OTRA',
});

const CENTER_ASSIGNMENT_ROLES = Object.freeze({
  SCHOOL_MANAGER: 'RESPONSABLE_CENTRO',
  TEACHER: 'PROFESOR',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'ALUMNO',
  FAMILY: 'FAMILIA',
  OTHER: 'OTRO',
});

const GROUP_ASSIGNMENT_ROLES = Object.freeze({
  TUTOR: 'TUTOR',
  TEACHER: 'PROFESOR',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDENT: 'ALUMNO',
  FAMILY: 'FAMILIA',
  OTHER: 'OTRO',
});

const CONSENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
});

const CONSENT_AUDIT_ACTIONS = Object.freeze({
  CONSENT_CREATED: 'CONSENT_CREATED',
  CONSENT_ACCEPTED: 'CONSENT_ACCEPTED',
  CONSENT_REJECTED: 'CONSENT_REJECTED',
  CONSENT_REVOKED: 'CONSENT_REVOKED',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  CONSENT_VIEWED: 'CONSENT_VIEWED',
  LEGAL_VERSION_CREATED: 'LEGAL_VERSION_CREATED',
  LEGAL_VERSION_UPDATED: 'LEGAL_VERSION_UPDATED',
});

const PUBLIC_USER_FIELDS = [
  'id',
  'name',
  'email',
  'role',
  'isActive',
  'schoolId',
  'groupId',
  'linkedStudentId',
  'birthDate',
  'ageRange',
  'createdAt',
  'updatedAt',
];

module.exports = {
  ROLES,
  UNICORN_GENDERS,
  CENTER_TYPES,
  ACADEMIC_YEAR_STAGES,
  CENTER_ASSIGNMENT_ROLES,
  GROUP_ASSIGNMENT_ROLES,
  CONSENT_STATUSES,
  CONSENT_AUDIT_ACTIONS,
  PUBLIC_USER_FIELDS,
};
